### ISSUE TITLE
Liquibase broken with Turkish

### ISSUE THREAD

**Issue by camsaul** [liquibase/liquibase.github.com#125]
This is with 3.6.3.

Setting my language to Turkish (`-Duser.country=TR -Duser.language=tr`) seems to break things. 

Specifically, I was seeing this stacktrace:

```java
java.lang.NullPointerException
	at liquibase.changelog.StandardChangeLogHistoryService.getRanChangeSets(StandardChangeLogHistoryService.java:310)
	at liquibase.changelog.AbstractChangeLogHistoryService.upgradeChecksums(AbstractChangeLogHistoryService.java:66)
	at liquibase.changelog.StandardChangeLogHistoryService.upgradeChecksums(StandardChangeLogHistoryService.java:293)
	at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:1221)
	at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1284)
	at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1274)
	at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1270)
```

I looked at the line in question, and saw

```java
String fileName = rs.get("FILENAME").toString();
```

So my first guess was that for one reason or another the keys in `rs` were getting translated. I fired up a REPL, and sure enough:

```clj
{"DEPLOYMENT_İD" "6650456162",
 "ORDEREXECUTED" 99,
 "DATEEXECUTED" #inst "2019-01-05T01:07:36.212-00:00",
 "TAG" nil,
 "CONTEXTS" nil,
 "LABELS" nil,
 "DESCRİPTİON" "addUniqueConstraint constraintName=idx_uniq_field_table_id_parent_id_name, tableName=metabase_field; sql",
 "MD5SUM" "8:274bb516dd95b76c954b26084eed1dfe",
 "İD" "99",
 "LİQUİBASE" "3.6.2",
 "FİLENAME" "migrations/000_migrations.yaml",
 "EXECTYPE" "EXECUTED",
 "AUTHOR" "camsaul",
 "COMMENTS" "Added 0.32.0"}
```

As you can see, in Turkish the key is getting saved as `FİLENAME` instead of `FILENAME`. This definitely doesn't seem right -- this map is for internal consumption and keys shouldn't be translated.

**Comment by camsaul** [comment]
Related? https://github.com/liquibase/liquibase/pull/751

**Comment by camsaul** [comment]
PR to fix it is here https://github.com/liquibase/liquibase/pull/857
