### ISSUE TITLE
No inverse to liquibase.change.core.RawSQLChange created

### ISSUE THREAD

**Issue by DrErique** [liquibase/liquibase.github.com#264]
## Expected Behavior
On the Liquibase Page ( https://www.liquibase.org/documentation ) there is an example for Liquibase formatted sql with Rollback option :

--liquibase formatted sql

--changeset nvoxland:1
create table test1 (
    id int primary key,
    name varchar(255)
);
--rollback drop table test1;

--changeset nvoxland:2
insert into test1 (id, name) values (1, 'name 1');
insert into test1 (id, name) values (2, 'name 2');

--changeset nvoxland:3 dbms:oracle
create sequence seq_test;

I installed Liquibase Version 3.8.0 and tried out the example.
It doesen't work and produces the message in the title. 

My expectation would be that "liquibase rollback" simply drops the table "test1".

## Actual Behavior
Error Message after liquibase rollbacksql

C:\Users\Administrator\LiquibaseProj>liquibase rollbacksql test3
Starte Liquibase am Fr, 08 Nov 2019 16:57:33 MEZ (Version 3.8.0, kompiliert am 2019-08-15T20:38:06Z)
Liquibase Community 3.8.0 by Datical
Rolling Back Changeset:sql/006_testskript.sql::3::nvoxland
Unerwarteter Fehler bei der Ausf├╝hrung von Liquibase: No inverse to liquibase.change.core.RawSQLChange created
liquibase.exception.RollbackFailedException: liquibase.exception.RollbackImpossibleException: No inverse to liquibase.change.core.RawSQLChange created
        at liquibase.changelog.ChangeSet.rollback(ChangeSet.java:725) ~[liquibase.jar:na]
        at liquibase.changelog.visitor.RollbackVisitor.visit(RollbackVisitor.java:40) ~[liquibase.jar:na]
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83) ~[liquibase.jar:na]
        at liquibase.Liquibase.rollback(Liquibase.java:727) ~[liquibase.jar:na]
        at liquibase.Liquibase.rollback(Liquibase.java:691) ~[liquibase.jar:na]
        at liquibase.Liquibase.rollback(Liquibase.java:670) ~[liquibase.jar:na]
        at liquibase.integration.commandline.Main.doMigration(Main.java:1283) [liquibase.jar:na]
        at liquibase.integration.commandline.Main.run(Main.java:209) [liquibase.jar:na]
        at liquibase.integration.commandline.Main.main(Main.java:132) [liquibase.jar:na]
Caused by: liquibase.exception.RollbackImpossibleException: No inverse to liquibase.change.core.RawSQLChange created
        at liquibase.change.AbstractChange.generateRollbackStatementsFromInverse(AbstractChange.java:469) ~[liquibase.jar:na]
        at liquibase.change.AbstractChange.generateRollbackStatements(AbstractChange.java:442) ~[liquibase.jar:na]
        at liquibase.database.AbstractJdbcDatabase.executeRollbackStatements(AbstractJdbcDatabase.java:1302) ~[liquibase.jar:na]
        at liquibase.changelog.ChangeSet.rollback(ChangeSet.java:711) ~[liquibase.jar:na]
        ... 8 common frames omitted

## Steps to Reproduce the Problem

  1. Actual Liquibase Version 3.8.0
  2. ChangeLog <includeAll path="C:\\Users\Administrator\LiquibaseProj\sql"/>
  3. .sql File like in the example from Liquibase Page to C:\\Users\Administrator\LiquibaseProj\sql
  4. liquibase tag test1
  5. liquibase update
  6. liquibase rollbacksql test1

## Specifications (if applicable)

  - Version: Liquibase 3.8.0
  - Platform: Windows
  - Subsystem: Oracle
  - Driver: oracle.jdbc.OracleDriver ; ojdbc8.jar

**Comment by SteveDonie** [comment]
Thanks for the feedback. The behavior you are experiencing is expected behavior, but the documentation for that example is not clear. 

The issue is that in order to roll back all the changesets, the changelog would need to have explicit rollback instructions for every single changeset. Your expectation that rollback would simply drop the table ignores that there are two other changesets that would first need to be rolled back before rolling back the changeset that creates the table, and no rollback instructions are provided for the other two changesets.

**Comment by SteveDonie** [comment]
For future reference - the example given is at the bottom of the page at https://www.liquibase.org/documentation/sql_format.html

**Comment by DrErique** [comment]
Hello Steve,

Thank you very much for the quick answer.
So if we want to have rollback option we have to write it for ALL changesets.

Unfortunately there are some confusing things written in the net about this error message in the context with liquibase.


Mit freundlichen Grüßen

Derik Wehrmann

_________________________________________________________________

Tel: -551 | Testmanager | IT SCM

Von: Steve Donie <notifications@github.com>
Gesendet: Freitag, 8. November 2019 17:59
An: liquibase/liquibase.github.com <liquibase.github.com@noreply.github.com>
Cc: Wehrmann, Derik <D.Wehrmann@wertgarantie.com>; Author <author@noreply.github.com>
Betreff: Re: [liquibase/liquibase.github.com] No inverse to liquibase.change.core.RawSQLChange created (#264)


For future reference - the example given is at the bottom of the page at https://www.liquibase.org/documentation/sql_format.html
