### ISSUE TITLE
Improve error message when tag 'column' is missing name

### ISSUE THREAD

**Issue by heese** [liquibase/liquibase.github.com#88]
If the tag `column` is wrongly used then Liquibase stops with a most confusing error message: `Unexpected error running Liquibase: Unknown Reason`. After debugging my XML file it became clear that I was not using `column` correctly -- the attribute `name` was missing.

It would be very helpful if Liquibase told the user that a required attribute is missing instead of throwing a `NullPointerException`.

```
liquibase.exception.MigrationFailedException: Migration failed for change set feature/[...]:
     Reason: java.lang.NullPointerException
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:586)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:43)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:73)
        at liquibase.Liquibase.update(Liquibase.java:200)
        at liquibase.Liquibase.update(Liquibase.java:258)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1058)
        at liquibase.integration.commandline.Main.run(Main.java:175)
        at liquibase.integration.commandline.Main.main(Main.java:94)
Caused by: java.lang.NullPointerException
        at liquibase.database.AbstractJdbcDatabase.escapeColumnName(AbstractJdbcDatabase.java:1009)
        ... [many] more
```

**Comment by nniesen** [comment]
I think you want this over in the https://github.com/liquibase/liquibase project. This is just the website/documentation project.

**Comment by heese** [comment]
I agree that it would fit better into the other project. However, the issue tracker feature has not been enabled there.

**Comment by nniesen** [comment]
Yeah, that one uses JIRA: https://liquibase.jira.com/issues

**Comment by heese** [comment]
Thanks.
